### ISSUE TITLE
unexpected sort "bvand"

### ISSUE THREAD

**Issue by polgreen** [kroening/fastsynth#93]
We don't parse bvand

test benchmark: 
https://github.com/SyGuS-Org/benchmarks/blob/master/comp/2018/General_Track/btr-am-base-index-scale-disp-solution-0.sl

**Comment by pkesseli** [comment]
I am actually getting `7: unknown symbol `modulo-shift'` for that file. This may be linked to our problems handling `let`, so I'll tackle #96 first.
